name: "Build Packages"

on: 
  workflow_call:
    secrets:
      CAP_GH_RELEASE_TOKEN:
        required: false

jobs:
  build:
    runs-on: 'ubuntu-22.04'
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.CAP_GH_RELEASE_TOKEN || github.token }}

      - name: 'Setup Tools'
        uses: ./.github/actions/setup-tools

      - name: 'Build Packages'
        shell: bash
        run: |
          pnpm lerna run build
