name: Plugin Upgrade

# Trigger manual
on:
  push:
    branches:
      - test/action-plugin-upgrade

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Tools
        uses: ./.github/actions/setup-tools

      - name: Verify Java version
        run: java -version

      #- name: Build Android
        #working-directory: plugin/android
        #run: ./gradlew clean build

      - name: Run Capacitor Plugin Migration
        working-directory: plugin
        run: npx @capacitor/plugin-migration-v6-to-v7@latest

      - name: Install PNPM dependencies
        run: pnpm install --no-frozen-lockfile
        working-directory: .

      - name: Build project
        run: pnpm run build
        working-directory: .

      - name: Build Android
        working-directory: plugin/android
        run: ./gradlew clean build