name: Plugin Upgrade

# Trigger manual
on:
  push:
    branches:
      - test/action-plugin-upgrade

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Tools
        uses: ./.github/actions/setup-tools
        with:
          skip-install-on-cache-hit: 'false'

      - name: Verify Java version
        run: java -version

      #- name: Build Android
        #working-directory: plugin/android
        #run: ./gradlew clean build

      - name: Run Capacitor Plugin Migration
        run: npx @capacitor/plugin-migration-v6-to-v7@latest