name: Plugin Upgrade

# Trigger manual
on:
  push:
    branches:
      - test/action-plugin-upgrade

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Tools
        uses: ./.github/actions/setup-tools

      - name: List installed Java versions
        run: /usr/libexec/java_home -V

      - name: Verify Java version
        run: java -version

      - name: Run Capacitor Plugin Migration
        working-directory: plugin
        run: npx @capacitor/plugin-migration-v6-to-v7@latest